### ISSUE TITLE
Invalid Logo on the Readme 

### ISSUE THREAD

**Issue by gssakash** [Serra-Technologies/serra#1]
Hi, I was checking out the project and noticed that there was a invalid Logo uploaded on the github over [here](https://github.com/Serra-Technologies/serra/blob/main/README.md) at the top this causing the README to not render it

**Comment by albertjstanley** [comment]
The README seems to be rendering fine on my end. Is this on Github or in your local development environment?

**Comment by gssakash** [comment]
No The README is fine, the logo for Serra doesn't seem to render at the top of the Readme

**Comment by alanhlwang** [comment]
Can you send a screenshot of what you’re seeing Akash?

**Comment by gssakash** [comment]
[screenshot](https://pasteboard.co/d2aFfOegWbMW.jpg) 
Here you go, this is what I see

**Comment by gssakash** [comment]
UPDATE : This seems to be fixed or else maybe it was a problem with my device. I checked back in a few hours and the logo did appear.

**Comment by albertjstanley** [comment]
Got it, thanks!
