### ISSUE TITLE
Question about the data sources supported

### ISSUE THREAD

**Issue by gssakash** [Serra-Technologies/serra#2]
This project seems pretty cool so far and I wanted to know what other data sources you guys are planning to implement soon. Will you guys be supporting NOSQL data sources as well?

**Comment by alanhlwang** [comment]
Thanks! and yep right now we are working on snowflake support (just added the reader and adding writer soon) as well as GCP, Redshift, Oracle, SQL Server. We will add support for NOSQL, planning on MongoDB first.

**Comment by alanhlwang** [comment]
Just wanted to follow up on this—we have released Snowflake support now!
